parameters:
- name: azureSubscriptionName
  type: string
  default: ''
- name: templateFileName
  type: string
  default: 'main.bicep'
- name: parametersFileName
  type: string
  default: 'parameters.json'
- name: command
  type: string
  default: 'validate'
- name: additionalArguments
  type: string
  default: ''
- name: deploymentName
  type: string
  default: 'azureADOCLIDeployment'
- name: resourceGroupName
  type: string
  default: ''

steps:
- task: AzureCLI@2
  displayName: 'az deployment group ${{ parameters.command }} command'
  inputs:
    azureSubscription: ${{ parameters.azureSubscriptionName }}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az deployment group ${{ parameters.command }} --resource-group ${{ parameters.resourceGroupName }} -n ${{ parameters.deploymentName }} --template-file ${{parameters.templateFileName}} --parameters ${{parameters.parametersFileName}} ${{ parameters.additionalArguments }}
