parameters:
- name: environmentName
  type: string
- name: serviceName
  type: string
- name: regionAbrv
  type: string
- name: azureContainerRegistryName
  type: string
- name: containerImageName
  type: string
- name: imageTagName
  type: string
- name: dockerFilePath
  type: string

jobs:
  - deployment: '${{ parameters.serviceName }}_container_${{ parameters.environmentName }}_${{ parameters.regionAbrv }}'
    environment: ${{ parameters.environmentName }}
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
          deploy:

            steps:
            - checkout: self
    
            - template: ../tasks/docker-task.yaml
              parameters:
                azureContainerRegistryName: '${{ parameters.azureContainerRegistryName }}'
                repositoryName: '${{ parameters.containerImageName }}'
                command: 'buildAndPush'
                dockerfileLocation: '${{ parameters.dockerFilePath }}/Dockerfile'
                tags: |
                  $(imageTagName)
                  latest